# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85f21517cdfe32243aaeee8e02a2c2a7d2b2cabeabf317dbec28932fc8312fdbe6894a6e775c2fdfb201477c6262e413d8c9ff77e4aafb9c3fcbdc740dd92350

test:
  secret_key_base: 234e2b4b71adb4bcc14d5fead5763a5a25013726c0c449715887ede131bbe679f152252d65f128ad89d172a7d999b7393b3175d6fb8b158fd2b31257ebdd16ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
